### ISSUE TITLE
Erorr: f is not a function

### ISSUE THREAD

**Issue by mdikov** [mashpie/i18n-node#428]
After I upgraded to 0.8.6 from 0.8.3 I started getting the error "" in one of my mocha tests. I stepped in with the debugger and i noticed that `f` get's compiled as an object and not as a function in `i18n.__ = function i18nTranslate(phrase) {`.

![image](https://user-images.githubusercontent.com/1004698/77777899-6f280180-700d-11ea-97be-87ddcc02bb5a.png)

This particular key is an object, which in the past I was able to translate as an object and iterate over the translated strings.

```
  "roles": {
    "role1": "role1 name",
    "role2": "role2 name"
  }
```

My setup does enable object notation:

```
i18n.configure({
  directory: `${__dirname}/../../shared/locales`,
  objectNotation: true,
  updateFiles: false,
  defaultLocale: 'en',
  api: {
    __mf: 'translate',
    getLocale: 'locale'
  }
});
```

Is there a breaking change I am missing?

**Comment by mashpie** [comment]
There has been a major version upgrade on messageformat in release 0.8.4 which also required a compatibility setting to keep passing my tests:

```js
    // now head over to Messageformat
    // and try to cache instance
    if (MessageformatInstanceForLocale[targetLocale]) {
      mf = MessageformatInstanceForLocale[targetLocale];
    } else {
      mf = new Messageformat(targetLocale);

      // @see https://messageformat.github.io/messageformat/MessageFormat#disablePluralKeyChecks__anchor
      mf.disablePluralKeyChecks();
      mf.compiledFunctions = {};
      MessageformatInstanceForLocale[targetLocale] = mf;
    }

    // let's try to cache that function
```

to be honest I can't tell wether the older messageformat compiled to functions or objects as I never tested on types but on results (https://github.com/mashpie/i18n-node/blob/master/test/i18n.mf.js)

**Comment by mdikov** [comment]
Yes the older version did compile to objects in the above scenario.  Perhaps before process we can add another check and if the message is an object iterate over the keys and translate each one of them?

**Comment by w4-jake** [comment]
Hi there,

Thank you for all of your work on this helpful library. I apologize if I should open a new issue rather than reply to this closed one -- I am not sure what the best etiquette is.

I am also a user who sees the 'f is not a function' error after upgrading i18n to 0.8.6 from 0.8.3 (and also after upgrading to the latest minor version of 0.11.x). Thank you for your explanation above about the connection to messageformat, but I am not quite sure what I should do to be able to update i18n. So for now I have locked i18n to 0.8.3 until I figure out how to upgrade.

If it is helpful, here is my i18n config below:

```
import path from 'path'

i18n.configure({
      directory: path.join(__dirname, '../locales'),
      locales: ['en', 'ko'],
      fallbacks: {
        'ko-KR': 'ko',
        ko: 'en'
      },
      defaultLocale: 'ko',
      queryParameter: 'hl',
      updateFiles: true,
      autoReload: true,
      indent: '  ',
      extension: '.json',
      objectNotation: true
    })
```

And my yarn.lock file's resolved dependencies for installing the newest version of i18n (messageformat's version is resolved to 2.3.0):

```
i18n@0.11.1:
  version "0.11.1"
  resolved "https://registry.yarnpkg.com/i18n/-/i18n-0.11.1.tgz#f06a37afbb37bd3e9714ce15f436dccc6146ded2"
  integrity sha512-j9JGOlvbUatVU5cXua+AHilotkt0wRI4ZEhkyh/v/tKcwbtMjpauxjrBcFBqTCz+Ew6Xr7cCJkA+4DLYQB1YUg==
  dependencies:
    debug "*"
    make-plural "^6.2.1"
    math-interval-parser "^2.0.1"
    messageformat "^2.3.0"
    mustache "^4.0.1"
    sprintf-js "^1.1.2"

messageformat@^2.3.0:
  version "2.3.0"
  resolved "https://registry.yarnpkg.com/messageformat/-/messageformat-2.3.0.tgz#de263c49029d5eae65d7ee25e0754f57f425ad91"
  integrity sha512-uTzvsv0lTeQxYI2y1NPa1lItL5VRI8Gb93Y2K2ue5gBPyrbJxfDi/EYWxh2PKv5yO42AJeeqblS9MJSh/IEk4w==
  dependencies:
    make-plural "^4.3.0"
    messageformat-formatters "^2.0.1"
    messageformat-parser "^4.1.2"
```

Please let me know what more information I can provide.

**Comment by mashpie** [comment]
Hi @w4-jake and @mdikov 

are you able to provide a reproducible setup as gist or repo?

**Comment by w4-jake** [comment]
Hmm have had some difficulty reproducing on a brand new repo. (I suppose this is in general good news actually.) Let me try to duplicate the issue by making the code more similar to my project and I will share once I have good information. Thanks.

**Comment by mashpie** [comment]
well... this is good news. Could be that any of an `npm update` or `yarn update` is failing pulling newest version. A common solution is to cleanUp node_modules and/or `yarn cache clean`
